GET http://localhost:3211/users

###
GET http://localhost:3211/products

###
GET http://localhost:3211/products/f84e618e-9eb7-424f-992d-b74a80509416
###
GET http://localhost:3211/users/bagol 212

###
POST http://localhost:3211/users
Content-Type: application/json


{
     
     "name": "mifta2",
     "email": "mifta2@gmail.com",
     "password": "mifta2",
     "confirmPassword":"mifta2",
     "role":"admin"
}

###
POST http://localhost:3211/products
Content-Type: application/json


{
     "name": "rokok 5",
     "price": 20000
}
###
POST http://localhost:3211/users
Content-Type: application/json


{
     "name": "asuuuu",
     "email": "angge@gmail.com",
     "password": "angger",
     "confirmPassword":"angger",
     "role":"user"
}

###
PATCH http://localhost:3211/users/88f5be1d-a405-4209-8d7b-364a392e96ce
Content-Type: application/json


{
     "name": "asuu",
     "email": "angge@gmail.com",
     "password": "asu",
     "confirmPassword":"asu",
     "role":"user"
}

###


###
DELETE http://localhost:3211/users/a27ab658-6065-4742-af8e-55cefd705b0


###

POST http://localhost:3211/login
Content-Type: application/json


{
     
     "email": "mifta@gmail.com",
     "password": "mifta"
}

###

POST http://localhost:3211/login
Content-Type: application/json

{
       "email": "angger@gmail.com",
     "password": "angger"
     }
###
GET http://localhost:3211/me
     

###
DELETE http://localhost:3211/logout

###
PATCH http://localhost:3211/products/88f5be1d-a405-4209-8d7b-364a392e96ce
Content-Type: application/json


{
     "name": "asu tenan",
      "price": 100
}
###
DELETE http://localhost:3211/products/35720429-062c-4d29-9524-011a99ecf84b
